fix: update submodule paths and improve installation logging

diff --git a/LoonEnv b/LoonEnv
--- a/LoonEnv
+++ b/LoonEnv
@@ -224,8 +224,8 @@ install_dependency() {
 ########################################
 require_zedsdk() {
     log "Checking for ZED SDK installation at /usr/local/zed..."
-    if [[ -d "/usr/local/zed" ]]; then
-        ZED_VERSION=$(sudo cat /usr/local/zed/VERSION)
+    if [[ -f "/usr/local/zed/zed-config-version.cmake" ]]; then
+        ZED_VERSION=$(sudo cat /usr/local/zed/zed-config-version.cmake | grep "set(PACKAGE_VERSION \"" | sed -E 's/set\(PACKAGE_VERSION "(.*)"\)/\1/')
         log "Found ZED SDK version $ZED_VERSION"
     else
         echo "Error: ZED SDK not found. Please install it and try again." >&2
@@ -473,11 +473,11 @@ installation() {
 
     # Requirements for installing docker, ros, and zedsdk
     if [[ "$INSTALL_DEPS" -eq 1 ]]; then
-        log "Require APT-GET for dependency installation"
+        log "[Installation] Require APT-GET for dependency installation"
         require_command "apt-get" \
             "apt-get is required to install dependencies. Please install apt-get or use install without --install-deps and try again." 
 
-        log "Require curl for dependency installation"
+        log "[Installation] Require curl for dependency installation"
 
         install_dependency "curl" \
             "curl is required to download dependencies. Please install curl and try again." \
@@ -512,13 +512,16 @@ installation() {
         "git is required to clone the Loon-E repository. Please install git and try again." \
         "sudo apt-get update && sudo apt-get install -y git"
 
-    log "Git is available. Proceeding with installation."
+    log "[Installation] Git is available. Proceeding with installation."
 
     # Check for NVIDIA GPU and drivers
     require_command "nvidia-smi" \
         "NVIDIA GPU not detected. Ensure you are using Jetpack on a compatible NVIDIA Jetson device with proper drivers installed."
 
+    log "[Installation] Checking zed sdk installation..."
     require_zedsdk
+
+    log "[Installation] All dependencies are installed. Proceeding with Loon-Env installation."
 }
 
 ################################
@@ -531,34 +534,35 @@ installation() {
 #  Exports environment variables for the workspace and docker images
 ################################
 set_variables() {
-    log "Checking for existing environment variable setup in ~/.loon_env_setup.bash..."
+    log "[Set Variables] Checking for existing environment variable setup in ~/.loon_env_setup.bash..."
     if [[ -f "$HOME/.loon_env_setup.bash" ]]; then
-        log "Existing environment variable setup found. Skipping variable setup."
+        log "[Set Variables] Existing environment variable setup found. Skipping variable setup."
         
     else
-        run echo "export LOONE_FILES_DIR=\"$PATH_INSTALL\"" >> ~/.loon_env_setup.bash
-        run echo "export LOONE_WORKSPACE_DIR=\"$WORKSPACE_DIR\"" >> ~/.loon_env_setup.bash
-        run echo "export LOONE_SETUP_SCRIPT=\"\$HOME/.loon_env_setup.bash\"" >> ~/.loon_env_setup.bash
-        run echo "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp" >> ~/.loon_env_setup.bash
-        run echo "export ROS_DOMAIN_ID=0" >> ~/.loon_env_setup.bash
-        run echo "export ROS_LOCALHOST_ONLY=0" >> ~/.loon_env_setup.bash
-        log "Environment variables set and exported to ~/.loon_env_setup.bash"
+        run 'echo "export LOONE_FILES_DIR='$PATH_INSTALL' >>' ~/.loon_env_setup.bash
+        run 'echo "export LOONE_WORKSPACE_DIR='$WORKSPACE_DIR' >>' ~/.loon_env_setup.bash
+        run 'echo "export LOONE_SETUP_SCRIPT='$HOME'/.loon_env_setup.bash >> ~/.loon_env_setup.bash'
+        run 'echo "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp >> ~/.loon_env_setup.bash'
+        run 'echo "export ROS_DOMAIN_ID=0 >> ~/.loon_env_setup.bash'
+        run 'echo "export ROS_LOCALHOST_ONLY=0 >> ~/.loon_env_setup.bash'
+        run 'echo "export ZED_SDK_VERSION="'$ZED_VERSION'" >> ~/.loon_env_setup.bash'
+        log "[Set Variables] Environment variables set and exported to ~/.loon_env_setup.bash"
     fi
-    log "Set ~/.bashrc to source ~/.loon_env_setup.bash if it exists"
+    log "[Set Variables] Setting ~/.bashrc to source ~/.loon_env_setup.bash if it exists"
     if ! grep -q "source ~/.loon_env_setup.bash" ~/.bashrc; then
-        run echo "source ~/.loon_env_setup.bash" >> ~/.bashrc
-        log "Added source command to ~/.bashrc"
+        run 'echo "source ~/.loon_env_setup.bash">> ~/.bashrc'
+        log "[Set Variables] Added source command to ~/.bashrc"
     else
-        log "Source command already exists in ~/.bashrc. Skipping."
+        log "[Set Variables] Source command already exists in ~/.bashrc. Skipping."
     fi
 
-    log "Setting group permissions for $GROUP_NAME to access $PATH_INSTALL"
-    run sudo chown -R :"$GROUP_NAME" "$PATH_INSTALL"
-    log "Done. Setting permissions to 644 for ~/.loon_env_setup.bash"
-    run chmod 644 ~/.loon_env_setup.bash
-    log "Permissions set for ~/.loon_env_setup.bash"
+    log "[Set Variables] Setting group permissions for $GROUP_NAME to access $PATH_INSTALL"
+    run 'sudo chown -R :'$GROUP_NAME $PATH_INSTALL
+    log "[Set Variables] Done. Setting permissions to 644 for ~/.loon_env_setup.bash"
+    run 'chmod 644 ~/.loon_env_setup.bash'
+    log "[Set Variables] Permissions set for ~/.loon_env_setup.bash"
     
-    log "Environment variable setup complete."
+    log "[Set Variables] Environment variable setup complete."
 }
 
 
@@ -589,18 +593,18 @@ setup_workspace() {
 
     local src_dir="$WORKSPACE_DIR"
 
-    log "Creating ROS 2 workspace at $WORKSPACE_DIR..."
-    run mkdir -p "$src_dir"
+    log "[Setup Workspace] Creating ROS 2 workspace at $WORKSPACE_DIR..."
+    run 'mkdir -p '$src_dir
     
-    log "Moving ./src/loon_ws to $WORKSPACE_DIR/loon_ws if it exists..."
+    log "[Setup Workspace] Moving ./src/loon_ws to $WORKSPACE_DIR/loon_ws if it exists..."
     if [[ -d "./src/loon_ws" ]]; then
         run mv "./src/loon_ws" "$WORKSPACE_DIR/loon_ws"
-        log "Moved loon_ws to workspace directory."
+        log "[Setup Workspace] Moved loon_ws to workspace directory."
     else
         echo "[WARNING] No existing loon_ws found in ./src. Skipping move." >&2
     fi
 
-    log "Downloading a ton of git repostiories for zed wrapper"
+    log "[Setup Workspace] Downloading a ton of git repostiories for zed wrapper"
     # TODO
     run wget 'https://github.com/ros/xacro/archive/refs/tags/'${XACRO_VERSION}+'.tar.gz -O - | tar -xvz && mv xacro-' + ${XACRO_VERSION} + "$WORKSPACE_DIR" + '/zed_ws/src/xacro'
     run wget 'https://github.com/ros/diagnostics/archive/refs/tags/'${DIAGNOSTICS_VERSION}+'.tar.gz -O - | tar -xvz && mv diagnostics-' + ${DIAGNOSTICS_VERSION} + "$WORKSPACE_DIR" + '/zed_ws/src/diagnostics'
@@ -614,23 +618,23 @@ setup_workspace() {
     run wget 'https://github.com/pal-robotics/backward_ros/archive/refs/tags/'${BACKWARD_ROS_VERSION} + '.tar.gz -O - | tar -xvz && mv backward_ros-' + ${BACKWARD_ROS_VERSION} + "$WORKSPACE_DIR" + '/zed_ws/src/backward_ros' && \
     run 'cp -r geographic-info/geographic_msgs/ ' + "$WORKSPACE_DIR" + '/zed_ws/src/geographic-info/ && \ rm -rf geographic-info'
 
-    log "Moving ./src/zed_ws to $WORKSPACE_DIR/zed_ws if it exists..."
+    log "[Setup Workspace] Moving ./src/zed_ws to $WORKSPACE_DIR/zed_ws if it exists..."
     if [[ -d "./src/zed_ws" ]]; then
         run mv "./src/zed_ws" "$WORKSPACE_DIR/zed_ws"
-        log "Moved zed_ws to workspace directory."
+        log "[Setup Workspace] Moved zed_ws to workspace directory."
     else
         echo "[WARNING] No existing zed_ws found in ./src. Skipping move." >&2
     fi
 
-    log "Moving ./src/docker to $WORKSPACE_DIR/docker if it exists..."
+    log "[Setup Workspace] Moving ./src/docker to $WORKSPACE_DIR/docker if it exists..."
     if [[ -d "./src/docker" ]]; then
         run mv "./src/docker" "$WORKSPACE_DIR/docker"
-        log "Moved docker to workspace directory."
+        log "[Setup Workspace] Moved docker to workspace directory."
     else
         echo "[WARNING] No existing docker found in ./src. Skipping move." >&2
     fi
 
-    log "Subdirectories for loon_e and zedx created in workspace src."
+    log "[Setup Workspace] Subdirectories for loon_e and zedx created in workspace src."
 }
 
 ##################################
@@ -648,40 +652,40 @@ setup_workspace() {
 #######################################
 install_loon_env() {
     migrate_old_installation
-    log "Installing Loon-Env assets of $VERSION to $PATH_INSTALL"
-    run sudo mkdir -p "$PATH_INSTALL/assets"
+    log "[Install ENV] Installing Loon-Env assets of $VERSION to $PATH_INSTALL"
+    run 'sudo mkdir -p ' $PATH_INSTALL/assets
 
-    log "Copying assets or overwriting to $PATH_INSTALL/assets"
-    run sudo cp -r "$ASSETS_DIR/." "$PATH_INSTALL/assets/"
+    log "[Install ENV] Copying assets or overwriting to $PATH_INSTALL/assets"
+    run 'sudo cp -r '$ASSETS_DIR'/.' $PATH_INSTALL/assets'/'
 
     # asset permissions to group and read/write for owner and group, read for others
-    log "Setting permissions for $PATH_INSTALL/assets to group ownership of $GROUP_NAME and read write for owner and group, read for others"
-    run sudo chown -R :"$GROUP_NAME" "$PATH_INSTALL/assets"
-    run sudo chmod -R 774 "$PATH_INSTALL/assets"
+    log "[Install ENV] Setting permissions for $PATH_INSTALL/assets to group ownership of $GROUP_NAME and read write for owner and group, read for others"
+    run 'sudo chown -R :'$GROUP_NAME $PATH_INSTALL/assets
+    run 'sudo chmod -R 774 ' $PATH_INSTALL/assets
 
-    log "Loon-Env assets installed to $PATH_INSTALL/assets with permissions set."
+    log "[Install ENV] Loon-Env assets installed to $PATH_INSTALL/assets with permissions set."
 
-    log "Moving copy of Loon-Env script to $LOON_E_SCRIPT_INSTALL"
-    run sudo mkdir -p "$(dirname "$LOON_E_SCRIPT_INSTALL")"
-    if [[ ! -f "$LOON_E_SOURCE" ]]; then
-        echo "Error: LoonE source not found at $LOON_E_SOURCE" >&2
+    log "[Install ENV] Moving copy of Loon-Env script to $LOONE_SCRIPT_INSTALL"
+    run 'sudo mkdir -p "$(dirname '${LOONE_SCRIPT_INSTALL}')'
+    if [[ ! -f "$LOONE_SOURCE" ]]; then
+        echo "Error: LoonE source not found at $LOONE_SOURCE" >&2
         exit 1
     fi
-    run sudo cp "$LOON_E_SOURCE" "$LOON_E_SCRIPT_INSTALL"
+    run sudo cp "$LOONE_SOURCE" "$LOONE_SCRIPT_INSTALL"
     
-    log "Loon-Env script copied to $LOON_E_SCRIPT_INSTALL"
+    log "[Install ENV] Loon-Env script copied to $LOONE_SCRIPT_INSTALL"
 
     # Set group ownership and permissions for the script
-    run sudo chown :"$GROUP_NAME" "$LOON_E_SCRIPT_INSTALL"
+    run sudo chown :"$GROUP_NAME" "$LOONE_SCRIPT_INSTALL"
 
     # Make the script executable
-    run sudo chmod 755 "$LOON_E_SCRIPT_INSTALL"
+    run sudo chmod 755 "$LOONE_SCRIPT_INSTALL"
     
-    log "Permissions set for $LOON_E_SCRIPT_INSTALL: group ownership to $GROUP_NAME and executable by all users."
+    log "[Install ENV] Permissions set for $LOONE_SCRIPT_INSTALL: group ownership to $GROUP_NAME and executable by all users."
 
     # Verify installation
-    if [[ -f "$LOON_E_SCRIPT_INSTALL" ]]; then
-        log "Loon-Env script installed successfully at $LOON_E_SCRIPT_INSTALL."
+    if [[ -f "$LOONE_SCRIPT_INSTALL" ]]; then
+        log "[Install ENV] Loon-Env script installed successfully at $LOONE_SCRIPT_INSTALL."
     else
         echo "Error: Failed to install Loon-Env script." >&2
         exit 1
@@ -689,7 +693,7 @@ install_loon_env() {
 
     # verify assets installation
     if [[ -d "$PATH_INSTALL/assets" ]]; then
-        log "Loon-Env assets installed successfully at $PATH_INSTALL/assets."
+        log "[Install ENV] Loon-Env assets installed successfully at $PATH_INSTALL/assets."
     else
         echo "Error: Failed to install Loon-Env assets." >&2
         exit 1
@@ -738,10 +742,9 @@ else
 fi
 
 log "Detecting various system information for installation..."
-
-L4T_VERSION="$(cat /etc/nv_tegra_release 2>/dev/null | grep -oE 'R[0-9]+T[0-9]+' || echo "unknown")" # Default to unknown if not found
-USERNAME="$(id -un)"
+L4T_VERSION="$(sed -n 's/^# \(R[0-9]\+\).*, REVISION: \([0-9.]\+\).*/\1.\2/p' /etc/nv_tegra_release 2>/dev/null || echo "unknown")"
 THIS_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+USERNAME="$(whoami)"
 USER_HOME="$(eval echo "~$USERNAME")"
 
 log "Detected OS: $NAME $VERSION_ID"
@@ -752,4 +755,24 @@ log "Script directory: $THIS_SCRIPT_DIR"
 
 require_non_root
 
+create_group_and_add_user
+installation
+set_variables
+install_loon_env
 setup_workspace
+
+echo "Loon-Env installation complete! Please restart your terminal or run 'source ~/.bashrc' to start using Loon-Env."
+cat <<EOF
+        QUACK!
+⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⡶⠿⠿⠷⣶⣄⠀⠀⠀⠀⠀
+⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⡿⠁⠀⠀⢀⣀⡀⠙⣷⡀⠀⠀⠀
+⠀⠀⠀⡀⠀⠀⠀⠀⠀⢠⣿⠁⠀⠀⠀⠘⠿⠃⠀⢸⣿⣿⣿⣿
+⠀⣠⡿⠛⢷⣦⡀⠀⠀⠈⣿⡄⠀⠀⠀⠀⠀⠀⠀⣸⣿⣿⣿⠟
+⢰⡿⠁⠀⠀⠙⢿⣦⣤⣤⣼⣿⣄⠀⠀⠀⠀⠀⢴⡟⠛⠋⠁⠀
+⣿⠇⠀⠀⠀⠀⠀⠉⠉⠉⠉⠉⠁⠀⠀⠀⠀⠀⠈⣿⠀⠀⠀
+⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⡇⠀⠀⠀
+⣿⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⡇⠀⠀⠀
+⠸⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⡿⠀⠀⠀⠀
+⠀⠹⣷⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣰⡿⠀⠀⠀⠀
+⠀⠀⠀⠉⠙⠛⠿⠶⣶⣶⣶⣶⣶⠶⠿⠟⠛⠀⠀⠀⠀⠀⠀
+EOF
